# Generated by Django 3.2.12 on 2022-03-30 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=3000, verbose_name='Введите ссылку на документ')),
                ('format', models.PositiveIntegerField(choices=[(0, 'MicrosoftOffice (.docx)'), (1, 'LibreOffice (.odt)')], default=0, verbose_name='Выберите формат документа')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'queries',
                'managed': True,
            },
        ),
    ]
