# Generated by Django 3.2.12 on 2022-04-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frkpapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queries',
            options={'managed': True, 'verbose_name': 'Запрос', 'verbose_name_plural': 'Запросы'},
        ),
        migrations.AddField(
            model_name='queries',
            name='blank',
            field=models.PositiveIntegerField(choices=[(0, 'Служебная записка')], default=0, verbose_name='Выберите бланк'),
        ),
        migrations.AlterField(
            model_name='queries',
            name='format',
            field=models.PositiveIntegerField(choices=[(0, 'MicrosoftOffice (.docx)'), (1, 'LibreOffice (.ott)')], default=0, verbose_name='Выберите формат документа'),
        ),
    ]
