# Generated by Django 4.0.2 on 2022-05-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frkpapp', '0002_auto_20220405_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='queries',
            name='delete',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='queries',
            name='format',
            field=models.PositiveIntegerField(choices=[(0, 'MicrosoftOffice (.docx)'), (1, 'LibreOffice (.odt)')], default=0, verbose_name='Выберите формат документа'),
        ),
    ]
