# Generated by Django 4.0.2 on 2022-05-25 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frkpapp', '0003_queries_delete_alter_queries_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queries',
            name='delete',
        ),
    ]
