# Generated by Django 4.0.2 on 2022-05-31 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frkpapp', '0004_remove_queries_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('query', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='frkpapp.queries')),
                ('kind', models.CharField(max_length=3000, verbose_name='Вид документа')),
                ('content', models.CharField(max_length=3000, verbose_name='Краткое содержание')),
            ],
            options={
                'db_table': 'document',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id_doc', models.OneToOneField(db_column='id_doc', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='children', serialize=False, to='frkpapp.document')),
                ('fio', models.CharField(max_length=3000, verbose_name='Исполнитель')),
                ('phone', models.CharField(max_length=3000, verbose_name='Номер исполнителя')),
                ('email', models.CharField(max_length=3000, verbose_name='Электорнная адрес исполнителя')),
            ],
            options={
                'db_table': 'actors',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Signers',
            fields=[
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='frkpapp.document')),
                ('fio', models.CharField(max_length=3000, verbose_name='Подписант')),
                ('role', models.CharField(max_length=3000, verbose_name='Должность подписанта')),
                ('suborganization', models.CharField(max_length=3000, verbose_name='Подразделение подписанта')),
            ],
            options={
                'db_table': 'signers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Correspondents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=3000, verbose_name='Адресат')),
                ('role', models.CharField(max_length=3000, verbose_name='Должность адресата')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frkpapp.document')),
            ],
            options={
                'db_table': 'correspondents',
                'managed': True,
            },
        ),
    ]
