# Generated by Django 4.0.2 on 2022-05-31 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frkpapp', '0007_rename_actors_performers_alter_performers_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signers',
            old_name='suborganization',
            new_name='dep',
        ),
    ]
