# Generated by Django 4.0.2 on 2022-05-31 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frkpapp', '0008_rename_suborganization_signers_dep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performers',
            old_name='phone',
            new_name='contacts',
        ),
        migrations.RemoveField(
            model_name='performers',
            name='email',
        ),
    ]
